-- ---------------------------
-- Creating new column (TOTAL_SALE)
-- ---------------------------

ALTER TABLE order_items
ADD COLUMN total_sale FLOAT;

UPDATE order_items
SET total_sale = quantity * price_per_unit;

 
-- ---------------------------
-- Data Overview
-- ---------------------------
 
select * from category;
select * from customers;
select * from sellers;
select * from products;
select * from orders;
select * from order_items;
select * from payments;
select * from shipping;
select * from inventory;



-- ---------------------------
-- 19 Advanced Business Problems
-- ---------------------------

/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/

SELECT 
	p.product_id,
	p.product_name,
    count(quantity) as total_quantity_sold,
    round(sum(oi.total_sale),2) as total_sale
FROM order_items oi
JOIN products p
ON p.product_id = oi.product_id
GROUP BY p.product_id
ORDER BY 3 desc
LIMIT 10;



/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/

SELECT 
	cg.category_name,
    round(sum(oi.total_sale),2) as total_revenue,
    round(
			sum(oi.total_sale) / (select sum(total_sale) from order_items)*100,2
            ) as contribution_pct
FROM order_items oi 
JOIN products p
ON p.product_id = oi.product_id
JOIN category cg
ON cg.category_id = p.category_id
GROUP BY 1
ORDER BY 3 DESC;	



/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/

SELECT
	c.customer_id,
    concat(c.first_name,' ',c.last_name)as customer_name,
    count(c.customer_id) as total_orders,
    round(avg(oi.total_sale),2) as average_order_value
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY 1
HAVING COUNT(c.customer_id)>5
ORDER BY 3 desc ;


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/

WITH monthly_sales as (
	SELECT 
		year(o.order_date) as year,
        month(o.order_date) as month,
        SUM(oi.total_sale) as monthly_sales
	FROM orders o
    JOIN order_items oi
    ON o.order_id = oi.order_id
    GROUP BY 2,1
	)
SELECT 
	year,
    month,
    round(monthly_sales,2) as current_month_sale,
    round(lag(monthly_sales) over(order by year, month),2) as last_month_sale
FROM monthly_sales
ORDER BY 1,2;    
	


/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/

SELECT 
	customer_id,
    concat(first_name,' ',last_name) as customer_name,
    state	
FROM customers
WHERE customer_id not in
						(SELECT customer_id FROM orders);



/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/


WITH ranking_table as
					(
					SELECT 
						c.state as state,
						cg.category_name as category,
						sum(oi.total_sale) as total_sale,
						rank() over(partition by c.state order by sum(oi.total_sale) asc) rn
					FROM order_items oi
					JOIN products p
					ON oi.product_id = p.product_id
					JOIN category cg
					ON cg.category_id = p.category_id
					JOIN orders o
					ON oi.order_id = o.order_id
					JOIN customers c
					ON o.customer_id = c.customer_id
					GROUP BY 1,2
					)
SELECT 
	state,
    category,
    round(total_sale,2)
FROM ranking_table 
WHERE rn =1;


/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

SELECT 
	c.customer_id,
    concat(c.first_name,' ',c.last_name) as customer_name,
    round(sum(total_sale),2) as CLTV,
    dense_rank() over(order by sum(total_sale) desc) as cx_ranking
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi 
ON o.order_id = oi.order_id
GROUP BY 1,2;



/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT 
	p.product_id,
    p.product_name,
	i.stock as current_stock_left,
    i.warehouse_id,
    i.last_stock_date
FROM inventory i
JOIN products p
ON i.product_id = p.product_id
WHERE stock <10;



/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

SELECT
	c.customer_id,
    concat(c.first_name,' ',c.last_name) as customer_name,
    c.state,
	o.order_id,
    o.order_date,
    order_status,
    s.shipping_provider,
    datediff(s.shipping_date, o.order_date) as days_took_to_ship
FROM orders o 
JOIN shipping s
ON o.order_id = s.order_id
JOIN customers c
ON c.customer_id = o.customer_id
WHERE datediff(s.shipping_date, o.order_date)>3;



/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT
	payment_status,
    count(payment_status) as total_cnt ,
    count(payment_status) / ( select count(*) from payments) * 100 as Payment_status_Rate 
FROM payments
GROUP BY 1;


/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/

WITH top_seller as (
					SELECT 
						s.seller_id,
						s.seller_name,
						round(sum(oi.total_sale),2) as total_sales_value      
					FROM sellers s
					JOIN orders o
					ON s.seller_id = o.seller_id
					JOIN order_items oi
					ON oi.order_id = o.order_id
					GROUP BY 1,2
					ORDER BY 3 desc
					LIMIT 5
                    ),

seller_reports as (
					SELECT o.seller_id,
						ts.seller_name,
						o.order_status,
						COUNT(*) as total_orders
					FROM orders as o
					JOIN top_seller ts
					ON ts.seller_id = o.seller_id
					WHERE order_status not in ('Inprogress', 'Returned')
					GROUP BY 1,2,3)

SELECT 
	sr.seller_id,
	sr.seller_name,
    tss.total_sales_value,
	SUM(CASE WHEN sr.order_status = 'Completed' THEN sr.total_orders ELSE 0 END) as Completed_orders,
	SUM(CASE WHEN sr.order_status = 'Cancelled' THEN sr.total_orders ELSE 0 END) as Cancelled_orders,
	SUM(sr.total_orders) as total_orders,
	round(SUM(CASE WHEN sr.order_status = 'Completed' THEN sr.total_orders ELSE 0 END)/
	SUM(sr.total_orders)* 100,2) as successful_orders_percentage
FROM seller_reports sr
JOIN top_seller tss
ON tss.seller_id = sr.seller_id
GROUP BY 1, 2;



/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT 
	product_id,
	product_name,
    round(profit,2) as profit,
	round(profit_margin,2) as profit_margin,
    rank() over(order by profit_margin desc) as product_ranking
FROM 
	(SELECT 
		p.product_id,
        p.product_name,
        sum(oi.total_sale - (p.cogs * oi.quantity)) as profit,
        sum(oi.total_sale - (p.cogs * oi.quantity)) / sum(oi.total_sale) * 100 as profit_margin
	 FROM products p
	 JOIN order_items oi
	 ON oi.product_id = p.product_id
     GROUP BY 1,2
     ) as t;



/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/


SELECT
	p.product_id,
    p.product_name,
    COUNT(*) as total_unit_sold,
    sum(case when o.order_status = 'Returned' then 1 else 0 end) as total_returned,
    round(sum(case when o.order_status = 'Returned' then 1 else 0 end) / count(*) *100,2) as return_pct
FROM order_items as oi
JOIN products as p
ON oi.product_id = p.product_id
JOIN orders as o
ON o.order_id = oi.order_id
GROUP BY 1, 2
ORDER BY 4 desc
LIMIT 10;



/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

SELECT 
	o.order_id,
    o.order_date,
    o.seller_id,
    o.order_status,
    p.payment_date,
    p.payment_status,
    c.customer_id,
    concat(c.first_name,' ',c.last_name) as customer_name,
    state
FROM orders o
JOIN payments p
ON o.order_id = p.order_id
JOIN shipping s
ON s.order_id = o.order_id
JOIN customers c
ON c.customer_id = o.customer_id
WHERE p.payment_status = 'payment successed'
	and delivery_status = 'shipped';


/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

/*We cannot calculate the last 6 months from the current date because 
the last order year in the dataset is 2024. So we will assume the last 
date as 30-07-2024, and any seller who has not made a sale in the last 
6 months from this date will be considered inactive. */


SELECT 
    s.seller_id,
    s.seller_name,
    MAX(o.order_date) AS last_sale_date,
    SUM(oi.total_sale) AS total_sales
FROM sellers s
JOIN orders o 
ON o.seller_id = s.seller_id
JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY s.seller_id, s.seller_name
HAVING MAX(o.order_date) < (
        SELECT DATE_SUB(MAX(order_date), INTERVAL 6 MONTH)
        FROM orders
);


/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/

SELECT 
    c.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    COUNT(o.order_id) AS total_orders,
    SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returns,
    CASE 
        WHEN SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) > 5 
        THEN 'Returning'
        ELSE 'New'
    END AS customer_category
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, customer_name
ORDER BY total_returns DESC;



/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/


SELECT * 
FROM(
	SELECT 
		c.state,
		CONCAT(c.first_name,' ',c.last_name) AS customer_name,
		COUNT(o.order_id) as total_orders,
		round(sum(oi.total_sale),2) as total_sale,
        dense_rank() over(partition by c.state order by count(o.order_id) desc) as rn
	FROM customers c
	JOIN orders o
	ON c.customer_id = o.customer_id
	JOIN order_items oi
	ON oi.order_id = o.order_id
	GROUP BY 1,2
    ) as t1
WHERE rn <= 5;



/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

SELECT 
	s.shipping_provider,
    count(oi.order_id) as order_handle,
    round(sum(oi.total_sale),2) as total_revenue_handled,
    coalesce(avg(datediff(s.return_date , s.shipping_date)),0) as average_days
FROM shipping s 
JOIN order_items oi
ON oi.order_id = s.order_id
GROUP BY 1;

/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result

Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/

WITH last_year_sale as (
		SELECT 
			p.product_id,
            p.product_name,
            p.category_id,
            round(SUM(oi.total_sale),2) as revenue
        FROM products p
        JOIN order_items oi
        ON p.product_id = oi.product_id
        JOIN orders o
        ON o.order_id = oi.order_id
		WHERE year(o.order_date)='2022'
        GROUP BY 1,2
        ),

current_year_sale as (
		SELECT 
			p.product_id,
            p.product_name,
            p.category_id,
            round(SUM(oi.total_sale),2) as revenue
        FROM products p
        JOIN order_items oi
        ON p.product_id = oi.product_id
        JOIN orders o
        ON o.order_id = oi.order_id
		WHERE year(o.order_date)='2023'
        GROUP BY 1,2
        )        

SELECT
	cs.product_id,
    cs.product_name,
    ctg.category_name,
	ls.revenue as last_year_revenue_2022,
	cs.revenue as current_year_revenue_2023,
	round(ls.revenue - cs.revenue,2) as rev_diff,
	ROUND((cs.revenue - ls.revenue)/ls.revenue * 100, 2) as reveneue_dec_ratio
FROM last_year_sale as ls
JOIN current_year_sale as cs
ON ls.product_id = cs.product_id
JOIN category ctg
ON ctg.category_id = cs.category_id
WHERE 
	ls.revenue > cs.revenue
ORDER BY reveneue_dec_ratio 
LIMIT 10; 


